### PR TITLE
Fix repeated use of annotated on ParameterizedTypeName

### LINKED ISSUE #358: Annotation base on List type will got duplicate code generator
Test code:

if type is List 

```
TypeName pet = ClassName.get(String.class);
        pet = ParameterizedTypeName.get(JAVA_LIST, pet);
```
and more than one annotation decleared , the first one will always duplicated:

```
        pet = pet.annotated(AnnotationSpec.builder(REQUEST_BODY).build());
        pet = pet.annotated(AnnotationSpec.builder(JAKARTA_VALID).build());
```

will got code:

```
@RequestBody @RequestBody @Valid List<String> example
```

[SingleTest.java](https://github.com/user-attachments/files/23498302/SingleTest.java)

### PR DESCRIPTION
**Pull request by pkoenig10**
Fixes https://github.com/palantir/javapoet/issues/358

### CODE REVIEW

File: javapoet/src/main/java/com/palantir/javapoet/ParameterizedTypeName.java [hunk 1]
```diff
@@ -43,7 +43,8 @@ private ParameterizedTypeName(
             List<TypeName> typeArguments,
             List<AnnotationSpec> annotations) {
         super(annotations);
-        this.rawType = checkNotNull(rawType, "rawType == null").annotated(annotations);
+        this.rawType =
+                checkNotNull(rawType, "rawType == null").withoutAnnotations().annotated(annotations);
```
Comment (aldexis) [inline javapoet/src/main/java/com/palantir/javapoet/ParameterizedTypeName.java]: It seems a bit wrong to create intermediary rawType multiple times.

I'm wondering whether we could
- Get rid of the constructor taking an annotations arg
- Have the rawType be provided with the annotations already (e.g. replace https://github.com/palantir/javapoet/blob/1c5573db4d721ceac9192f567373030df0225846/javapoet/src/main/java/com/palantir/javapoet/ParameterizedTypeName.java#L71-L73 by `new ParameterizedTypeName(enclosingType, rawType.annotated(annotations), typeArguments);`
- Get the annotations from `rawType.annotations()` to pass to `super`

That constructor seems to only ever be called (with a non-empty list anyway) from that one place

Comment (pkoenig10) [reply javapoet/src/main/java/com/palantir/javapoet/ParameterizedTypeName.java]: Thanks for the suggestion, this is much nicer.

This actually revealed and fixed a separate bug where

```java
ParameterizedTypeName get(ClassName rawType, TypeName... typeArguments)
```

would silently drop any annotations that on `rawType`.

I've added a test to verify this, now fixed, behavior.

File: javapoet/src/main/java/com/palantir/javapoet/ArrayTypeName.java [hunk 2]
```diff
@@ -43,6 +44,11 @@ public TypeName componentType() {
         return componentType;
     }
 
+    @Override
+    public ArrayTypeName annotated(AnnotationSpec... annotations) {
+        return annotated(Arrays.asList(annotations));
+    }
```
Comment (pkoenig10) [inline javapoet/src/main/java/com/palantir/javapoet/ArrayTypeName.java:50]: `annotated(List)` is overridden to return the more specific type. I don't see any reason why we wouldn't want to do the same for `annotated(AnnotationSpec...)`.

**Review by aldexis — APPROVED** [review]
